// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsMax.Data;

#nullable disable

namespace OpsMax.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108023343_AddPaymentSourceCreatedDate")]
    partial class AddPaymentSourceCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpsMax.DTO.InvoiceLineDto", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InvoiceNumberID")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCodeID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OpsMax.DTO.ViewModels.CollectionSummaryVM", b =>
                {
                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<decimal>("OverCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnderCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idOrderCollected")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_CollectionsSummary", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.Property<int>("idOrderCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrderCollected"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceNumberID")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrderCollected");

                    b.HasIndex("OrderStatusID");

                    b.ToTable("_tblCollection", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CollectionLineEntity", b =>
                {
                    b.Property<int>("idOrderLineCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrderLineCollected"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCodeID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderCollectedID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrderLineCollected");

                    b.HasIndex("OrderCollectedID");

                    b.ToTable("_tblCollectionLines", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.OrderStatus", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idStatus"));

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("idStatus");

                    b.ToTable("_tblOrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            idStatus = 1,
                            StatusCode = "Not Collected",
                            StatusDescription = "Not Collected"
                        },
                        new
                        {
                            idStatus = 2,
                            StatusCode = "Partially Collected",
                            StatusDescription = "Partially Collected"
                        },
                        new
                        {
                            idStatus = 3,
                            StatusCode = "Fully Collected",
                            StatusDescription = "Fully Collected"
                        },
                        new
                        {
                            idStatus = 4,
                            StatusCode = "Over Collected",
                            StatusDescription = "Over Collected"
                        });
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCaptured")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentSources");
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSourceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentSourceId")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSourceId");

                    b.ToTable("PaymentSourceDocuments");
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.HasOne("OpsMax.Models.OrderStatus", null)
                        .WithMany("CollectionsEntity")
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsMax.Models.CollectionLineEntity", b =>
                {
                    b.HasOne("OpsMax.Models.CollectionEntity", "Collection")
                        .WithMany("Lines")
                        .HasForeignKey("OrderCollectedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSourceDocument", b =>
                {
                    b.HasOne("OpsMax.Models.PaymentSource", "PaymentSource")
                        .WithMany("Documents")
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSource");
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("OpsMax.Models.OrderStatus", b =>
                {
                    b.Navigation("CollectionsEntity");
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSource", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
