// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpsMax.Data;

#nullable disable

namespace OpsMax.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpsMax.DTO.InvoiceLineDto", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InvoiceNumberID")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCodeID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OpsMax.DTO.ViewModels.GLAccountVM", b =>
                {
                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlAccountId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OpsMax.DTO.ViewModels.SupplierGRVVM", b =>
                {
                    b.Property<string>("GrvNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.Property<int>("idOrderCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrderCollected"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceNumberID")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrderCollected");

                    b.HasIndex("OrderStatusID");

                    b.ToTable("_tblCollection", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CollectionLineEntity", b =>
                {
                    b.Property<int>("idOrderLineCollected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrderLineCollected"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCodeID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderCollectedID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrderLineCollected");

                    b.HasIndex("OrderCollectedID");

                    b.ToTable("_tblCollectionLines", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CustomerAllocation", b =>
                {
                    b.Property<int>("idCustomerAllocations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCustomerAllocations"));

                    b.Property<DateTime>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("LoadID")
                        .HasColumnType("int");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCustomerAllocations");

                    b.HasIndex("LoadID");

                    b.ToTable("CustomerAllocations", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Driver", b =>
                {
                    b.Property<int>("idDrivers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDrivers"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LicenseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDrivers");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Load", b =>
                {
                    b.Property<int>("idLoad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLoad"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimatedArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoadedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaizeStockCodeID")
                        .HasColumnType("int");

                    b.Property<decimal>("ShortageQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<int>("TruckID")
                        .HasColumnType("int");

                    b.HasKey("idLoad");

                    b.HasIndex("DriverID");

                    b.HasIndex("TruckID");

                    b.ToTable("Loads", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.LoadDocument", b =>
                {
                    b.Property<int>("idLoadDocuments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLoadDocuments"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoadID")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idLoadDocuments");

                    b.HasIndex("LoadID");

                    b.ToTable("LoadDocuments", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.OrderStatus", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idStatus"));

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("idStatus");

                    b.ToTable("_tblOrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            idStatus = 1,
                            StatusCode = "Not Collected",
                            StatusDescription = "Not Collected"
                        },
                        new
                        {
                            idStatus = 2,
                            StatusCode = "Partially Collected",
                            StatusDescription = "Partially Collected"
                        },
                        new
                        {
                            idStatus = 3,
                            StatusCode = "Fully Collected",
                            StatusDescription = "Fully Collected"
                        },
                        new
                        {
                            idStatus = 4,
                            StatusCode = "Over Collected",
                            StatusDescription = "Over Collected"
                        });
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSource", b =>
                {
                    b.Property<int>("idPaymentSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPaymentSource"));

                    b.Property<int>("Account")
                        .HasColumnType("int");

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("AccountName")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCaptured")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPaymentSource");

                    b.ToTable("PaymentSources", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSourceDocument", b =>
                {
                    b.Property<int>("idPaymentSourceDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPaymentSourceDoc"));

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentSourceID")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idPaymentSourceDoc");

                    b.HasIndex("PaymentSourceID");

                    b.ToTable("PaymentSourceDocuments", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Truck", b =>
                {
                    b.Property<int>("idTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTruck"));

                    b.Property<decimal>("CapacityTonnes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTruck");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.Views.CollectionSummaryView", b =>
                {
                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOrderCollected")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceNumberID")
                        .HasColumnType("int");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<decimal>("OverCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnderCollected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_CollectionsSummary", (string)null);
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.HasOne("OpsMax.Models.OrderStatus", null)
                        .WithMany("CollectionsEntity")
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsMax.Models.CollectionLineEntity", b =>
                {
                    b.HasOne("OpsMax.Models.CollectionEntity", "Collection")
                        .WithMany("Lines")
                        .HasForeignKey("OrderCollectedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("OpsMax.Models.CustomerAllocation", b =>
                {
                    b.HasOne("OpsMax.Models.Load", "Load")
                        .WithMany("Allocations")
                        .HasForeignKey("LoadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("OpsMax.Models.Load", b =>
                {
                    b.HasOne("OpsMax.Models.Driver", "Driver")
                        .WithMany("Loads")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpsMax.Models.Truck", "Truck")
                        .WithMany("Loads")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("OpsMax.Models.LoadDocument", b =>
                {
                    b.HasOne("OpsMax.Models.Load", "Load")
                        .WithMany("Documents")
                        .HasForeignKey("LoadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSourceDocument", b =>
                {
                    b.HasOne("OpsMax.Models.PaymentSource", "PaymentSource")
                        .WithMany("Documents")
                        .HasForeignKey("PaymentSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSource");
                });

            modelBuilder.Entity("OpsMax.Models.CollectionEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("OpsMax.Models.Driver", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("OpsMax.Models.Load", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("OpsMax.Models.OrderStatus", b =>
                {
                    b.Navigation("CollectionsEntity");
                });

            modelBuilder.Entity("OpsMax.Models.PaymentSource", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("OpsMax.Models.Truck", b =>
                {
                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
